name: E2E Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    # Only run E2E tests if secrets are available (not on forks)
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name == github.repository
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    
    - name: Get dependencies
      run: go mod download
    
    - name: Run E2E Tests
      if: env.TEST_BUCKET != ''
      env:
        TEST_BUCKET: ${{ secrets.TEST_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}
      run: |
        echo "Running E2E tests against bucket: $TEST_BUCKET"
        go test -v -tags=e2e -timeout=10m ./...
    
    - name: Skip E2E Tests
      if: env.TEST_BUCKET == ''
      run: echo "Skipping E2E tests - TEST_BUCKET not configured"